checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    dependency_paths:
        - lib/

build:
    environment:
        python: '3.6'
        postgresql: false
        redis: false

    dependencies:
        override:
            # Project depends
            - pip install aiodns cchardet ujson aiohttp asyncio beautifulsoup4
            # Coverage depends
            - pip install pylint>=1.8.1 mypy>=0.580 lxml coverage pytest pytest-cov

    project_setup:
        override:
            - python setup.py build --disable-steam-api
            - command: python setup.py install

    tests:
        override:
            - py-scrutinizer-run
            - command: pylint-run stlib --rcfile=pylintrc
            - command: mypy tests --linecoverage-report mypy.report
            - command: echo -n "!coverage.py: This is a private format, don't read it directly!">.mypy_coverage
            - command: cat mypy.report/coverage.json>>.mypy_coverage
              coverage:
                  file: '.mypy_coverage'
                  format: 'py-cc'
