checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    dependency_paths:
        - lib/

build:
    environment:
        python: '3.6'
        postgresql: false
        redis: false

    dependencies:
        override:
            # Project depends
            - pip install aiodns cchardet ujson aiohttp asyncio beautifulsoup4
            # Coverage depends
            - pip install pylint>=1.8.1 mypy>=0.580 lxml coverage pytest pytest-cov

    project_setup:
        before:
            - command: cd src/steam_api
            - command: image_id=$(docker create shypixie/steamworks_sdk)
            - command: docker cp $image_id:steamworks_sdk - > steamworks.tar.gz
            - command: tar xfv steamworks.tar.gz
            - command: cd ../..
        override:
            - python setup.py build
            - command: python setup.py install

    tests:
        override:
            - py-scrutinizer-run
            - command: pylint-run stlib --rcfile=pylintrc
            - command: mypy tests
            - command: py.test --cov=stlib tests
              coverage:
                  file: '.coverage'
                  format: 'py-cc'
